name: Issue Trigger

on:
  issues:
    types: [ opened,reopened ]
jobs:
  action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Login to Docker Registry
        run: echo "${{ secrets.REPO_PWD }}" | docker login -u ${{ secrets.REPO_USERNAME }} --password-stdin ${{ secrets.REPO_ENDPOINT }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute Python script
        run: python mover.py ${{ github.event.issue.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUES_ID: ${{ github.event.issue.number }}
          REPO_NAME: ${{ github.event.repository.full_name }}